# Generated by Django 5.1.6 on 2025-02-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_chat_quota_used_note_is_chat_note_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
