# Generated by Django 5.1.6 on 2025-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usertokenquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokenquota',
            name='total_tokens',
            field=models.IntegerField(default=500),
        ),
    ]
