# Generated by Django 5.1.6 on 2025-03-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usertokenquota_total_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='quota_limit',
            field=models.IntegerField(default=5),
        ),
    ]
