# Generated by Django 5.1.6 on 2025-03-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chat_quota_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='quota_limit',
            field=models.IntegerField(default=10),
        ),
    ]
