# Generated by Django 5.1.6 on 2025-03-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chat_quota_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='quota_limit',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='tokens_used',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_session',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserTokenQuota',
        ),
    ]
