# Generated by Django 5.1.6 on 2025-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_chat_quota_limit_remove_chat_tokens_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='remaining_messages',
            field=models.IntegerField(default=5),
        ),
    ]
