# Generated by Django 5.1.6 on 2025-03-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='remaining_messages',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
