# Generated by Django 5.1.6 on 2025-03-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_chat_options_remove_chat_remaining_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
