# Generated by Django 5.1.6 on 2025-03-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chat_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='remaining_messages',
            field=models.IntegerField(default=5),
        ),
    ]
