# Generated by Django 4.2.7 on 2025-04-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chat_remaining_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_automatic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='model_mode',
            field=models.CharField(default='GPT4 Correct', max_length=20),
        ),
    ]
